
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:1 (project)"
    message: |
      The system is: Windows - 10.0.19044 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:1 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.3.1+2badb37d1 for .NET Framework
      生成启动时间为 2023/3/12 16:17:19。
      节点 1 上的项目“E:\\绿洲\\华为挑战赛\\WindowsRelease\\SDK\\c++\\CMakeFiles\\3.26.0-rc6\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdC.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      ClCompile:
        E:\\VS\\VSstudio projects\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        E:\\VS\\VSstudio projects\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> E:\\绿洲\\华为挑战赛\\WindowsRelease\\SDK\\c++\\CMakeFiles\\3.26.0-rc6\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=E:\\VS\\VSstudio projects\\VC\\Tools\\MSVC\\14.33.31629\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate”执行 Touch 任务。
      已完成生成项目“E:\\绿洲\\华为挑战赛\\WindowsRelease\\SDK\\c++\\CMakeFiles\\3.26.0-rc6\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:01.39
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        E:/绿洲/华为挑战赛/WindowsRelease/SDK/c++/CMakeFiles/3.26.0-rc6/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:1 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.3.1+2badb37d1 for .NET Framework
      生成启动时间为 2023/3/12 16:17:21。
      节点 1 上的项目“E:\\绿洲\\华为挑战赛\\WindowsRelease\\SDK\\c++\\CMakeFiles\\3.26.0-rc6\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdCXX.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      ClCompile:
        E:\\VS\\VSstudio projects\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        E:\\VS\\VSstudio projects\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> E:\\绿洲\\华为挑战赛\\WindowsRelease\\SDK\\c++\\CMakeFiles\\3.26.0-rc6\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=E:\\VS\\VSstudio projects\\VC\\Tools\\MSVC\\14.33.31629\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
      已完成生成项目“E:\\绿洲\\华为挑战赛\\WindowsRelease\\SDK\\c++\\CMakeFiles\\3.26.0-rc6\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:00.63
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        E:/绿洲/华为挑战赛/WindowsRelease/SDK/c++/CMakeFiles/3.26.0-rc6/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "E:/cmake/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:1 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "E:/\u7eff\u6d32/\u534e\u4e3a\u6311\u6218\u8d5b/WindowsRelease/SDK/c++/CMakeFiles/CMakeScratch/TryCompile-yryfjl"
      binary: "E:/\u7eff\u6d32/\u534e\u4e3a\u6311\u6218\u8d5b/WindowsRelease/SDK/c++/CMakeFiles/CMakeScratch/TryCompile-yryfjl"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: E:/绿洲/华为挑战赛/WindowsRelease/SDK/c++/CMakeFiles/CMakeScratch/TryCompile-yryfjl
        
        Run Build Command(s):E:/VS/VSstudio projects/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_379bb.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.3.1+2badb37d1 for .NET Framework
        生成启动时间为 2023/3/12 16:17:22。
        节点 1 上的项目“E:\\绿洲\\华为挑战赛\\WindowsRelease\\SDK\\c++\\CMakeFiles\\CMakeScratch\\TryCompile-yryfjl\\cmTC_379bb.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_379bb.dir\\Debug\\”。
          正在创建目录“E:\\绿洲\\华为挑战赛\\WindowsRelease\\SDK\\c++\\CMakeFiles\\CMakeScratch\\TryCompile-yryfjl\\Debug\\”。
          正在创建目录“cmTC_379bb.dir\\Debug\\cmTC_379bb.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_379bb.dir\\Debug\\cmTC_379bb.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        ClCompile:
          E:\\VS\\VSstudio projects\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_379bb.dir\\Debug\\\\" /Fd"cmTC_379bb.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "E:\\cmake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.33.31630 版
          CMakeCCompilerABI.c
          版权所有(C) Microsoft Corporation。保留所有权利。
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_379bb.dir\\Debug\\\\" /Fd"cmTC_379bb.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "E:\\cmake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
        Link:
          E:\\VS\\VSstudio projects\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\绿洲\\华为挑战赛\\WindowsRelease\\SDK\\c++\\CMakeFiles\\CMakeScratch\\TryCompile-yryfjl\\Debug\\cmTC_379bb.exe" /INCREMENTAL /ILK:"cmTC_379bb.dir\\Debug\\cmTC_379bb.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/绿洲/华为挑战赛/WindowsRelease/SDK/c++/CMakeFiles/CMakeScratch/TryCompile-yryfjl/Debug/cmTC_379bb.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/绿洲/华为挑战赛/WindowsRelease/SDK/c++/CMakeFiles/CMakeScratch/TryCompile-yryfjl/Debug/cmTC_379bb.lib" /MACHINE:X64  /machine:x64 cmTC_379bb.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_379bb.vcxproj -> E:\\绿洲\\华为挑战赛\\WindowsRelease\\SDK\\c++\\CMakeFiles\\CMakeScratch\\TryCompile-yryfjl\\Debug\\cmTC_379bb.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_379bb.dir\\Debug\\cmTC_379bb.tlog\\unsuccessfulbuild”。
          正在对“cmTC_379bb.dir\\Debug\\cmTC_379bb.tlog\\cmTC_379bb.lastbuildstate”执行 Touch 任务。
        已完成生成项目“E:\\绿洲\\华为挑战赛\\WindowsRelease\\SDK\\c++\\CMakeFiles\\CMakeScratch\\TryCompile-yryfjl\\cmTC_379bb.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:00.61
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "E:/cmake/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:1 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "E:/\u7eff\u6d32/\u534e\u4e3a\u6311\u6218\u8d5b/WindowsRelease/SDK/c++/CMakeFiles/CMakeScratch/TryCompile-yh7to1"
      binary: "E:/\u7eff\u6d32/\u534e\u4e3a\u6311\u6218\u8d5b/WindowsRelease/SDK/c++/CMakeFiles/CMakeScratch/TryCompile-yh7to1"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: E:/绿洲/华为挑战赛/WindowsRelease/SDK/c++/CMakeFiles/CMakeScratch/TryCompile-yh7to1
        
        Run Build Command(s):E:/VS/VSstudio projects/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_e719a.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.3.1+2badb37d1 for .NET Framework
        生成启动时间为 2023/3/12 16:17:22。
        节点 1 上的项目“E:\\绿洲\\华为挑战赛\\WindowsRelease\\SDK\\c++\\CMakeFiles\\CMakeScratch\\TryCompile-yh7to1\\cmTC_e719a.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_e719a.dir\\Debug\\”。
          正在创建目录“E:\\绿洲\\华为挑战赛\\WindowsRelease\\SDK\\c++\\CMakeFiles\\CMakeScratch\\TryCompile-yh7to1\\Debug\\”。
          正在创建目录“cmTC_e719a.dir\\Debug\\cmTC_e719a.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_e719a.dir\\Debug\\cmTC_e719a.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        ClCompile:
          E:\\VS\\VSstudio projects\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_e719a.dir\\Debug\\\\" /Fd"cmTC_e719a.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "E:\\cmake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.33.31630 版
          CMakeCXXCompilerABI.cpp
          版权所有(C) Microsoft Corporation。保留所有权利。
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_e719a.dir\\Debug\\\\" /Fd"cmTC_e719a.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "E:\\cmake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          E:\\VS\\VSstudio projects\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\绿洲\\华为挑战赛\\WindowsRelease\\SDK\\c++\\CMakeFiles\\CMakeScratch\\TryCompile-yh7to1\\Debug\\cmTC_e719a.exe" /INCREMENTAL /ILK:"cmTC_e719a.dir\\Debug\\cmTC_e719a.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/绿洲/华为挑战赛/WindowsRelease/SDK/c++/CMakeFiles/CMakeScratch/TryCompile-yh7to1/Debug/cmTC_e719a.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/绿洲/华为挑战赛/WindowsRelease/SDK/c++/CMakeFiles/CMakeScratch/TryCompile-yh7to1/Debug/cmTC_e719a.lib" /MACHINE:X64  /machine:x64 cmTC_e719a.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_e719a.vcxproj -> E:\\绿洲\\华为挑战赛\\WindowsRelease\\SDK\\c++\\CMakeFiles\\CMakeScratch\\TryCompile-yh7to1\\Debug\\cmTC_e719a.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_e719a.dir\\Debug\\cmTC_e719a.tlog\\unsuccessfulbuild”。
          正在对“cmTC_e719a.dir\\Debug\\cmTC_e719a.tlog\\cmTC_e719a.lastbuildstate”执行 Touch 任务。
        已完成生成项目“E:\\绿洲\\华为挑战赛\\WindowsRelease\\SDK\\c++\\CMakeFiles\\CMakeScratch\\TryCompile-yh7to1\\cmTC_e719a.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:00.57
        
      exitCode: 0
...
